{{- if eq .Values.monitoring.tool "none" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pv-monitor-logging-config
  namespace: {{ .Values.rbac.namespace }}
data:
  log-file-config.sh: |
    #!/bin/bash
    LOG_FILE_PATH={{ .Values.logging.logFilePath }}
    touch $LOG_FILE_PATH
    bpftrace -e 'tracepoint:syscalls:sys_enter_openat /str(args->filename) =~ "/mnt/data"/ {
      printf("File opened: %s\n", str(args->filename));
    }' >> $LOG_FILE_PATH
{{- end }}
