apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pv-monitor-rolebinding
  namespace: {{ .Values.rbac.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccountName }}
    namespace: {{ .Values.rbac.namespace }}
roleRef:
  kind: Role
  name: pv-monitor-role
  apiGroup: rbac.authorization.k8s.io
